from django.contrib import admin

# Register your models here.
from . models import admin_addtax_table,admin_addbrand_table,admin_add_productlist_table, contact_table,reg_table,admin_adduser_table,admin_reg_table,admin_add_customer_table,admin_add_vendor_table,admin_addcategory_table,admin_add_role_table,admin_add_sale_table,admin_add_return_table,admin_add_stock_table,admin_add_purchase_tax_table,admin_add_expense_report_table,admin_add_customer_report_table,admin_add_quotation_table,admin_add_expense_list_table,addtax_table,addbrand_table,add_productlist_table,adduser_table,add_customer_table,add_vendor_table,addcategory_table,add_role_table,add_sale_table,add_return_table,add_stock_table,add_purchase_tax_table,add_expense_report_table,add_customer_report_table,add_quotation_table,add_expense_list_table
admin.site.register(contact_table)
admin.site.register(reg_table)
admin.site.register(admin_adduser_table)
admin.site.register(admin_reg_table)
admin.site.register(admin_add_customer_table)
admin.site.register(admin_add_vendor_table)
admin.site.register(admin_add_productlist_table)
admin.site.register(admin_addcategory_table)
admin.site.register(admin_addbrand_table)
admin.site.register(admin_addtax_table)
admin.site.register(admin_add_role_table)
admin.site.register(admin_add_sale_table)
admin.site.register(admin_add_return_table)
admin.site.register(admin_add_stock_table)
admin.site.register(admin_add_purchase_tax_table)
admin.site.register(admin_add_expense_report_table)
admin.site.register(admin_add_customer_report_table)
admin.site.register(admin_add_quotation_table)
admin.site.register(admin_add_expense_list_table)
admin.site.register(adduser_table)
admin.site.register(add_customer_table)
admin.site.register(add_vendor_table)
admin.site.register(add_productlist_table)
admin.site.register(addcategory_table)
admin.site.register(addbrand_table)
admin.site.register(addtax_table)
admin.site.register(add_role_table)
admin.site.register(add_sale_table)
admin.site.register(add_return_table)
admin.site.register(add_stock_table)
admin.site.register(add_purchase_tax_table)
admin.site.register(add_expense_report_table)
admin.site.register(add_customer_report_table)
admin.site.register(add_quotation_table)
admin.site.register(add_expense_list_table)
