from django.urls import path
from . import views

urlpatterns=[
    #landing page paths
    path('',views.index,name='index'),
    path('contact_form_submission',views.contact_form_submission,name='contact_form_submission'),
    path('cart',views.cart,name='cart'),
    path('invoice',views.invoice,name='invoice'),
    path('products',views.products,name='products'),
    path('productdetail',views.productdetail,name='productdetail'),
    #404 page
    path('error_page',views.error_page,name='error_page'),
    #user sigin or signup page paths
    path('sign',views.sign,name='sign'),
    path('signup_form_submission',views.signup_form_submission,name='signup_form_submission'),
    path('signin_form_submission',views.signin_form_submission,name='signin_form_submission'),

    path('logout',views.logout,name='logout'),
    path('dashboard/<int:id>',views.dashboard,name='dashboard'),
    path('addbrand/<int:id>',views.addbrand,name='addbrand'),
    path('addcategory',views.addcategory,name='addcategory'),
    path('addcustomer/<int:id>',views.addcustomer,name='addcustomer'),

    path('addcustomerreport/<int:id>',views.addcustomerreport,name='addcustomerreport'),
    path('add_customer_report_form_submission/<int:id>',views.add_customer_report_form_submission,name='add_customer_report_form_submission'),

    path('addexpense/<int:id>',views.addexpense,name='addexpense'),
    path('add_expense_list_form_submission/<int:id>',views.add_expense_list_form_submission,name='add_expense_list_form_submission'),

    path('addexpensereport/<int:id>',views.addexpensereport,name='addexpensereport'),
    path('add_expense_report_form_submission/<int:id>',views.add_expense_report_form_submission,name='add_expense_report_form_submission'),

    path('addpurchasetax/<int:id>',views.addpurchasetax,name='addpurchasetax'),
    path('add_purchase_tax_form_submission/<int:id>',views.add_purchase_tax_form_submission,name='add_purchase_tax_form_submission'),

    path('addquotation/<int:id>',views.addquotation,name='addquotation'),
    path('add_quotation_form_submission/<int:id>',views.add_quotation_form_submission,name='add_quotation_form_submission'),

    path('addreturn/<int:id>',views.addreturn,name='addreturn'),
    path('add_return_form_submission/<int:id>',views.add_return_form_submission,name='add_return_form_submission'),

    path('addrole/<int:id>',views.addrole,name='addrole'),
    path('add_role_form_submission/<int:id>',views.add_role_form_submission,name='add_role_form_submission'),

    path('addsale/<int:id>',views.addsale,name='addsale'),
    path('add_sale_form_submission/<int:id>',views.add_sale_form_submission,name='add_sale_form_submission'),

    path('addstock/<int:id>',views.addstock,name='addstock'),
    path('add_stock_form_submission/<int:id>',views.add_stock_form_submission,name='add_stock_form_submission'),

    path('addtax/<int:id>',views.addtax,name='addtax'),
    path('adduser/<int:id>',views.adduser,name='adduser'),
    path('addcategory/<int:id>',views.addcategory,name='addcategory'),
    path('addcategory_form_submission/<int:id>',views.addcategory_form_submission,name='addcategory_form_submission'),
    path('adduser_form_submission/<int:id>',views.adduser_form_submission,name='adduser_form_submission'),
    path('addvendor/<int:id>',views.addvendor,name='addvendor'),
    path('brands/<int:id>',views.brands,name='brands'),
    path('calenders/<int:id>',views.calenders,name='calenders'),
    path('chat/<int:id>',views.chat,name='chat'),
    path('customerreport/<int:id>',views.customerreport,name='customerreport'),
    path('customers/<int:id>',views.customers,name='customers'),
    path('editbrand/<int:row_id>/<int:logger_id>',views.editbrand,name='editbrand'),
    path('editcategory',views.editcategory,name='editcategory'),
    path('editcustomer/<int:row_id>/<int:logger_id>',views.editcustomer,name='editcustomer'),

    path('editcustomerreport/<int:row_id>/<int:logger_id>',views.editcustomerreport,name='editcustomerreport'),
    path('update_customer_report_form_submission/<int:row_id>/<int:logger_id>',views.update_customer_report_form_submission,name='update_customer_report_form_submission'),
    path('customer_report_delete/<int:row_id>/<int:logger_id>',views.customer_report_delete,name='customer_report_delete'),

    path('editexpense/<int:row_id>/<int:logger_id>',views.editexpense,name='editexpense'),
    path('update_expense_list_form_submission/<int:row_id>/<int:logger_id>',views.update_expense_list_form_submission,name='update_expense_list_form_submission'),
    path('expense_list_delete/<int:row_id>/<int:logger_id>',views.expense_list_delete,name='expense_list_delete'),

    path('editexpensereport/<int:row_id>/<int:logger_id>',views.editexpensereport,name='editexpensereport'),
    path('update_expense_report_form_submission/<int:row_id>/<int:logger_id>',views.update_expense_report_form_submission,name='update_expense_report_form_submission'),
    path('expense_report_delete/<int:row_id>/<int:logger_id>',views.expense_report_delete,name='expense_report_delete'),

    path('editpurchasetax/<int:row_id>/<int:logger_id>',views.editpurchasetax,name='editpurchasetax'),
    path('update_purchase_tax_form_submission/<int:row_id>/<int:logger_id>',views.update_purchase_tax_form_submission,name='update_purchase_tax_form_submission'),
    path('purchase_tax_delete/<int:row_id>/<int:logger_id>',views.purchase_tax_delete,name='purchase_tax_delete'),

    path('editquotation/<int:row_id>/<int:logger_id>',views.editquotation,name='editquotation'),
    path('update_quotation_form_submission/<int:row_id>/<int:logger_id>',views.update_quotation_form_submission,name='update_quotation_form_submission'),
    path('quotation_delete/<int:row_id>/<int:logger_id>',views.quotation_delete,name='quotation_delete'),

    path('editreturn/<int:row_id>/<int:logger_id>',views.editreturn,name='editreturn'),
    path('update_return_form_submission/<int:row_id>/<int:logger_id>',views.update_return_form_submission,name='update_return_form_submission'),
    path('return_delete/<int:row_id>/<int:logger_id>',views.return_delete,name='return_delete'),

    path('editrole/<int:row_id>/<int:logger_id>',views.editrole,name='editrole'),
    path('update_role_form_submission/<int:row_id>/<int:logger_id>',views.update_role_form_submission,name='update_role_form_submission'),
    path('role_delete/<int:row_id>/<int:logger_id>',views.role_delete,name='role_delete'),

    path('editsale/<int:row_id>/<int:logger_id>',views.editsale,name='editsale'),
    path('update_sale_form_submission/<int:row_id>/<int:logger_id>',views.update_sale_form_submission,name='update_sale_form_submission'),
    path('sale_delete/<int:row_id>/<int:logger_id>',views.sale_delete,name='sale_delete'),

    path('editstock/<int:row_id>/<int:logger_id>',views.editstock,name='editstock'),
    path('update_stock_form_submission/<int:row_id>/<int:logger_id>',views.update_stock_form_submission,name='update_stock_form_submission'),
    path('stock_delete/<int:row_id>/<int:logger_id>',views.stock_delete,name='stock_delete'),

    path('edittax/<int:row_id>/<int:logger_id>',views.edittax,name='edittax'),
    path('edituser/<int:row_id>/<int:logger_id>',views.edituser,name='edituser'),
    path('update_user_form_submission/<int:row_id>/<int:logger_id>',views.update_user_form_submission,name='update_user_form_submission'),
    path('user_delete/<int:row_id>/<int:logger_id>',views.user_delete,name='user_delete'),
    path('editcategory/<int:row_id>/<int:logger_id>',views.editcategory,name='editcategory'),
    path('update_category_form_submission/<int:row_id>/<int:logger_id>',views.update_category_form_submission,name='update_category_form_submission'),
    path('category_delete/<int:row_id>/<int:logger_id>',views.category_delete,name='category_delete'),
    path('editvendor/<int:row_id>/<int:logger_id>',views.editvendor,name='editvendor'),
    path('expensecategory/<int:id>',views.expensecategory,name='expensecategory'),
    path('expenselist/<int:id>',views.expenselist,name='expenselist'),
    path('expensereport/<int:id>',views.expensereport,name='expensereport'),
    path('profile',views.profile,name='profile'),
    path('purchasetaxreport/<int:id>',views.purchasetaxreport,name='purchasetaxreport'),
    path('quotations/<int:id>',views.quotations,name='quotations'),
    path('returns/<int:id>',views.returns,name='returns'),
    path('roles/<int:id>',views.roles,name='roles'),
    path('sales/<int:id>',views.sales,name='sales'),
    path('stockanalysis/<int:id>',views.stockanalysis,name='stockanalysis'),
    path('tax/<int:id>',views.tax,name='tax'),
    path('users/<int:id>',views.users,name='users'),
    path('vendors/<int:id>',views.vendors,name='vendors'),
    path('addproduct/<int:id>',views.addproduct,name='addproduct'),
    path('editproduct/<int:row_id>/<int:logger_id>',views.editproduct,name='editproduct'),
    path('productlist/<int:id>',views.productlist,name='productlist'),
    path('compose/<int:id>',views.compose,name='compose'),
    path('viewmail/<int:id>',views.viewmail,name='viewmail'),
    path('inbox/<int:id>',views.inbox,name='inbox'),
    path('add_customer_form_submission/<int:id>',views.add_customer_form_submission,name='add_customer_form_submission'),
    path('customer_update_form_submission/<int:row_id>/<int:logger_id>',views.customer_update_form_submission,name='customer_update_form_submission'),
    path('customer_delete/<int:row_id>/<int:logger_id>',views.customer_delete,name='customer_delete'),
    path('add_vendor_form_submission/<int:id>',views.add_vendor_form_submission,name='add_vendor_form_submission'),
    path('vendor_update_form_submission/<int:row_id>/<int:logger_id>',views.vendor_update_form_submission,name='vendor_update_form_submission'),
    path('vendor_delete/<int:row_id>/<int:logger_id>',views.vendor_delete,name='vendor_delete'),
    path('add_product_form_submission/<int:id>',views.add_product_form_submission,name='add_product_form_submission'),
    path('product_update_form_submission/<int:row_id>/<int:logger_id>',views.product_update_form_submission,name='product_update_form_submission'),
    path('product_delete/<int:row_id>/<int:logger_id>',views.product_delete,name='product_delete'),
    path('addbrand_form_submission/<int:id>',views.addbrand_form_submission,name='addbrand_form_submission'),
    path('brands_update_form_submission/<int:row_id>/<int:logger_id>',views.brands_update_form_submission,name='brands_update_form_submission'),
    path('brands_delete/<int:row_id>/<int:logger_id>',views.brands_delete,name='brands_delete'),
    path('addtax_form_submission/<int:id>',views.addtax_form_submission,name='addtax_form_submission'),
    path('tax_update_form_submission/<int:row_id>/<int:logger_id>',views.tax_update_form_submission,name='tax_update_form_submission'),
    path('tax_delete/<int:row_id>/<int:logger_id>',views.tax_delete,name='tax_delete'),

    
    #admin_dashboard page paths
    path('admin_signin',views.admin_signin,name='admin_signin'),
    path('admin_signup',views.admin_signup,name='admin_signup'),
    path('admin_signup_form_submission',views.admin_signup_form_submission,name='admin_signup_form_submission'),
    path('admin_signin_form_submission',views.admin_signin_form_submission,name='admin_signin_form_submission'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('admin_addbrand',views.admin_addbrand,name='admin_addbrand'),
    path('admin_addcategory',views.admin_addcategory,name='admin_addcategory'),
    path('admin_addcustomer',views.admin_addcustomer,name='admin_addcustomer'),

    path('admin_addcustomerreport',views.admin_addcustomerreport,name='admin_addcustomerreport'),
    path('admin_add_customer_report_form_submission',views.admin_add_customer_report_form_submission,name='admin_add_customer_report_form_submission'),

    path('admin_addexpense',views.admin_addexpense,name='admin_addexpense'),
    path('admin_add_expense_list_form_submission',views.admin_add_expense_list_form_submission,name='admin_add_expense_list_form_submission'),

    path('admin_addexpensereport',views.admin_addexpensereport,name='admin_addexpensereport'),
    path('admin_add_expense_report_form_submission',views.admin_add_expense_report_form_submission,name='admin_add_expense_report_form_submission'),

    path('admin_addpurchasetax',views.admin_addpurchasetax,name='admin_addpurchasetax'),
    path('admin_add_purchase_tax_form_submission',views.admin_add_purchase_tax_form_submission,name='admin_add_purchase_tax_form_submission'),

    path('admin_addquotation',views.admin_addquotation,name='admin_addquotation'),
    path('admin_add_quotation_form_submission',views.admin_add_quotation_form_submission,name='admin_add_quotation_form_submission'),

    path('admin_addreturn',views.admin_addreturn,name='admin_addreturn'),
    path('admin_add_return_form_submission',views.admin_add_return_form_submission,name='admin_add_return_form_submission'),

    path('admin_addrole',views.admin_addrole,name='admin_addrole'),
    path('admin_add_role_form_submission',views.admin_add_role_form_submission,name='admin_add_role_form_submission'),

    path('admin_addsale',views.admin_addsale,name='admin_addsale'),
    path('admin_add_sale_form_submission',views.admin_add_sale_form_submission,name='admin_add_sale_form_submission'),

    path('admin_addstock',views.admin_addstock,name='admin_addstock'),
    path('admin_add_stock_form_submission',views.admin_add_stock_form_submission,name='admin_add_stock_form_submission'),

    path('admin_addtax',views.admin_addtax,name='admin_addtax'),
    path('admin_adduser',views.admin_adduser,name='admin_adduser'),
    path('admin_addcategory',views.admin_addcategory,name='admin_addcategory'),
    path('admin_addcategory_form_submission',views.admin_addcategory_form_submission,name='admin_addcategory_form_submission'),
    path('admin_adduser_form_submission',views.admin_adduser_form_submission,name='admin_adduser_form_submission'),
    path('admin_addvendor',views.admin_addvendor,name='admin_addvendor'),
    path('admin_brands',views.admin_brands,name='admin_brands'),
    path('admin_calenders',views.admin_calenders,name='admin_calenders'),
    path('admin_chat',views.admin_chat,name='admin_chat'),
    path('admin_customerreport',views.admin_customerreport,name='admin_customerreport'),
    path('admin_customers',views.admin_customers,name='admin_customers'),
    path('admin_editbrand/<int:row_id>',views.admin_editbrand,name='admin_editbrand'),
    path('admin_editcategory',views.admin_editcategory,name='admin_editcategory'),
    path('admin_editcustomer/<int:row_id>',views.admin_editcustomer,name='admin_editcustomer'),

    path('admin_editcustomerreport/<int:row_id>',views.admin_editcustomerreport,name='admin_editcustomerreport'),
    path('update_admin_customer_report_form_submission/<int:row_id>',views.update_admin_customer_report_form_submission,name='update_admin_customer_report_form_submission'),
    path('admin_customer_report_delete/<int:row_id>',views.admin_customer_report_delete,name='admin_customer_report_delete'),

    path('admin_editexpense/<int:row_id>',views.admin_editexpense,name='admin_editexpense'),
    path('update_admin_expense_list_form_submission/<int:row_id>',views.update_admin_expense_list_form_submission,name='update_admin_expense_list_form_submission'),
    path('admin_expense_list_delete/<int:row_id>',views.admin_expense_list_delete,name='admin_expense_list_delete'),

    path('admin_editexpensereport/<int:row_id>',views.admin_editexpensereport,name='admin_editexpensereport'),
    path('update_admin_expense_report_form_submission/<int:row_id>',views.update_admin_expense_report_form_submission,name='update_admin_expense_report_form_submission'),
    path('admin_expense_report_delete/<int:row_id>',views.admin_expense_report_delete,name='admin_expense_report_delete'),

    path('admin_editpurchasetax/<int:row_id>',views.admin_editpurchasetax,name='admin_editpurchasetax'),
    path('update_admin_purchase_tax_form_submission/<int:row_id>',views.update_admin_purchase_tax_form_submission,name='update_admin_purchase_tax_form_submission'),
    path('admin_purchase_tax_delete/<int:row_id>',views.admin_purchase_tax_delete,name='admin_purchase_tax_delete'),

    path('admin_editquotation/<int:row_id>',views.admin_editquotation,name='admin_editquotation'),
    path('update_admin_quotation_form_submission/<int:row_id>',views.update_admin_quotation_form_submission,name='update_admin_quotation_form_submission'),
    path('admin_quotation_delete/<int:row_id>',views.admin_quotation_delete,name='admin_quotation_delete'),

    path('admin_editreturn/<int:row_id>',views.admin_editreturn,name='admin_editreturn'),
    path('update_admin_return_form_submission/<int:row_id>',views.update_admin_return_form_submission,name='update_admin_return_form_submission'),
    path('admin_return_delete/<int:row_id>',views.admin_return_delete,name='admin_return_delete'),

    path('admin_editrole/<int:row_id>',views.admin_editrole,name='admin_editrole'),
    path('update_admin_role_form_submission/<int:row_id>',views.update_admin_role_form_submission,name='update_admin_role_form_submission'),
    path('admin_role_delete/<int:row_id>',views.admin_role_delete,name='admin_role_delete'),

    path('admin_editsale/<int:row_id>',views.admin_editsale,name='admin_editsale'),
    path('update_admin_sale_form_submission/<int:row_id>',views.update_admin_sale_form_submission,name='update_admin_sale_form_submission'),
    path('admin_sale_delete/<int:row_id>',views.admin_sale_delete,name='admin_sale_delete'),

    path('admin_editstock/<int:row_id>',views.admin_editstock,name='admin_editstock'),
    path('update_admin_stock_form_submission/<int:row_id>',views.update_admin_stock_form_submission,name='update_admin_stock_form_submission'),
    path('admin_stock_delete/<int:row_id>',views.admin_stock_delete,name='admin_stock_delete'),

    path('admin_edittax/<int:row_id>',views.admin_edittax,name='admin_edittax'),
    path('admin_edituser/<int:row_id>',views.admin_edituser,name='admin_edituser'),
    path('update_admin_user_form_submission/<int:row_id>',views.update_admin_user_form_submission,name='update_admin_user_form_submission'),
    path('admin_user_delete/<int:row_id>',views.admin_user_delete,name='admin_user_delete'),
    path('admin_editcategory/<int:row_id>',views.admin_editcategory,name='admin_editcategory'),
    path('update_admin_category_form_submission/<int:row_id>',views.update_admin_category_form_submission,name='update_admin_category_form_submission'),
    path('admin_category_delete/<int:row_id>',views.admin_category_delete,name='admin_category_delete'),
    path('admin_editvendor/<int:row_id>',views.admin_editvendor,name='admin_editvendor'),
    path('admin_expensecategory',views.admin_expensecategory,name='admin_expensecategory'),
    path('admin_expenselist',views.admin_expenselist,name='admin_expenselist'),
    path('admin_expensereport',views.admin_expensereport,name='admin_expensereport'),
    path('admin_profile',views.admin_profile,name='admin_profile'),
    path('admin_purchasetaxreport',views.admin_purchasetaxreport,name='admin_purchasetaxreport'),
    path('admin_quotations',views.admin_quotations,name='admin_quotations'),
    path('admin_returns',views.admin_returns,name='admin_returns'),
    path('admin_roles',views.admin_roles,name='admin_roles'),
    path('admin_sales',views.admin_sales,name='admin_sales'),
    path('admin_stockanalysis',views.admin_stockanalysis,name='admin_stockanalysis'),
    path('admin_tax',views.admin_tax,name='admin_tax'),
    path('admin_users',views.admin_users,name='admin_users'),
    path('admin_vendors',views.admin_vendors,name='admin_vendors'),
    path('admin_addproduct',views.admin_addproduct,name='admin_addproduct'),
    path('admin_editproduct/<int:row_id>',views.admin_editproduct,name='admin_editproduct'),
    path('admin_productlist',views.admin_productlist,name='admin_productlist'),
    path('admin_compose',views.admin_compose,name='admin_compose'),
    path('admin_viewmail',views.admin_viewmail,name='admin_viewmail'),
    path('admin_inbox',views.admin_inbox,name='admin_inbox'),
    path('admin_add_customer_form_submission',views.admin_add_customer_form_submission,name='admin_add_customer_form_submission'),
    path('admin_customer_update_form_submission/<int:row_id>',views.admin_customer_update_form_submission,name='admin_customer_update_form_submission'),
    path('admin_customer_delete/<int:row_id>',views.admin_customer_delete,name='admin_customer_delete'),
    path('admin_add_vendor_form_submission',views.admin_add_vendor_form_submission,name='admin_add_vendor_form_submission'),
    path('admin_vendor_update_form_submission/<int:row_id>',views.admin_vendor_update_form_submission,name='admin_vendor_update_form_submission'),
    path('admin_vendor_delete/<int:row_id>',views.admin_vendor_delete,name='admin_vendor_delete'),
    path('admin_add_product_form_submission',views.admin_add_product_form_submission,name='admin_add_product_form_submission'),
    path('admin_product_update_form_submission/<int:row_id>',views.admin_product_update_form_submission,name='product_update_form_submission'),
    path('admin_product_delete/<int:row_id>',views.admin_product_delete,name='admin_product_delete'),
    path('admin_addbrand_form_submission',views.admin_addbrand_form_submission,name='admin_addbrand_form_submission'),
    path('admin_brands_update_form_submission/<int:row_id>',views.admin_brands_update_form_submission,name='admin_brands_update_form_submission'),
    path('admin_brands_delete/<int:row_id>',views.admin_brands_delete,name='admin_brands_delete'),
    path('admin_addtax_form_submission',views.admin_addtax_form_submission,name='admin_addtax_form_submission'),
    path('admin_tax_update_form_submission/<int:row_id>',views.admin_tax_update_form_submission,name='admin_tax_update_form_submission'),
    path('admin_tax_delete/<int:row_id>',views.admin_tax_delete,name='admin_tax_delete'),
    
]