# Generated by Django 4.0.1 on 2022-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_adduser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='adduser_table',
            name='logger_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
