# Generated by Django 4.0.1 on 2022-01-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_rename_adduser_table_admin_adduser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_reg_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('conpass', models.CharField(max_length=50)),
            ],
        ),
    ]
