# Generated by Django 4.0.1 on 2022-02-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0006_admin_reg_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_reg_table',
            name='conpass',
        ),
    ]
