# Generated by Django 4.0.1 on 2022-02-04 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_rename_add_customer_table_add_customer_form_submission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_customer_form_submission',
            new_name='add_customer_table',
        ),
    ]
