# Generated by Django 4.0.1 on 2022-02-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0010_rename_add_customer_form_submission_add_customer_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_vendor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_phone', models.IntegerField()),
                ('vendor_address', models.CharField(max_length=100)),
                ('vendor_city', models.CharField(max_length=100)),
                ('vendor_state', models.CharField(max_length=100)),
                ('vendor_country', models.CharField(max_length=100)),
                ('vendor_zipcode', models.IntegerField()),
            ],
        ),
    ]
