# Generated by Django 4.0.1 on 2022-02-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_add_vendor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_productlist_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_tax', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=100)),
                ('product_purchase_price', models.CharField(max_length=100)),
                ('product_selling_price', models.CharField(max_length=100)),
                ('product_sku', models.CharField(max_length=100)),
                ('product_description', models.CharField(max_length=100)),
            ],
        ),
    ]
