# Generated by Django 4.0.1 on 2022-02-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0012_add_productlist_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_category_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
    ]
