# Generated by Django 4.0.1 on 2022-02-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0013_add_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_category_table',
            name='logger_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
