# Generated by Django 4.0.1 on 2022-02-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0014_add_category_table_logger_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_category_table',
            new_name='admin_addcategory_table',
        ),
    ]
