# Generated by Django 4.0.1 on 2022-02-08 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0015_rename_add_category_table_admin_addcategory_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add_customer_table',
            new_name='admin_add_customer_table',
        ),
        migrations.RenameModel(
            old_name='add_productlist_table',
            new_name='admin_add_productlist_table',
        ),
        migrations.RenameModel(
            old_name='add_vendor_table',
            new_name='admin_add_vendor_table',
        ),
    ]
