# Generated by Django 4.0.1 on 2022-02-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0020_remove_admin_add_productlist_table_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_add_vendor_table',
            name='vendor_country',
        ),
        migrations.RemoveField(
            model_name='admin_add_vendor_table',
            name='vendor_phone',
        ),
        migrations.RemoveField(
            model_name='admin_add_vendor_table',
            name='vendor_state',
        ),
        migrations.RemoveField(
            model_name='admin_add_vendor_table',
            name='vendor_zipcode',
        ),
    ]
