# Generated by Django 4.0.1 on 2022-02-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0021_remove_admin_add_vendor_table_vendor_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_add_customer_table',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='admin_add_customer_table',
            name='customer_country',
        ),
        migrations.RemoveField(
            model_name='admin_add_customer_table',
            name='customer_state',
        ),
        migrations.RemoveField(
            model_name='admin_add_customer_table',
            name='customer_zipcode',
        ),
    ]
