# Generated by Django 4.0.1 on 2022-02-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0023_rename_user_role_admin_adduser_table_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add_role_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=100)),
            ],
        ),
    ]
