# Generated by Django 4.0.1 on 2022-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0026_admin_add_role_table_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_add_role_table',
            old_name='profile',
            new_name='create',
        ),
        migrations.AddField(
            model_name='admin_add_role_table',
            name='delete',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_add_role_table',
            name='edit',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_add_role_table',
            name='manage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
