# Generated by Django 4.0.1 on 2022-02-10 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0027_rename_profile_admin_add_role_table_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_add_role_table',
            old_name='create',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='admin_add_role_table',
            name='delete',
        ),
        migrations.RemoveField(
            model_name='admin_add_role_table',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='admin_add_role_table',
            name='manage',
        ),
    ]
