# Generated by Django 4.0.1 on 2022-02-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0028_rename_create_admin_add_role_table_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_add_role_table',
            name='account',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_add_role_table',
            name='notification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
