# Generated by Django 4.0.1 on 2022-02-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0029_admin_add_role_table_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_add_vendor_table',
            old_name='vendor_address',
            new_name='vendor_phone',
        ),
    ]
