# Generated by Django 4.0.1 on 2022-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0030_rename_vendor_address_admin_add_vendor_table_vendor_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_add_customer_table',
            name='customer_phone',
            field=models.CharField(max_length=100),
        ),
    ]
