# Generated by Django 4.0.1 on 2022-02-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0033_admin_add_productlist_table_logger_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add_sale_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('sold_by', models.CharField(max_length=100)),
                ('sold_to', models.CharField(max_length=100)),
                ('items_sold', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
    ]
