# Generated by Django 4.0.1 on 2022-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0034_admin_add_sale_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add_return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_email', models.CharField(max_length=100)),
                ('returned_dt', models.CharField(max_length=100)),
                ('returned_item', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
    ]
