# Generated by Django 4.0.1 on 2022-02-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0039_admin_add_expense_report_table_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add_customer_report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tot_sales', models.CharField(max_length=100)),
                ('tot_amt', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
    ]
