# Generated by Django 4.0.1 on 2022-02-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0040_admin_add_customer_report_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_add_quotation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=100)),
                ('customer', models.EmailField(max_length=254)),
                ('customer_email', models.CharField(max_length=100)),
                ('g_total', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
    ]
