# Generated by Django 4.0.1 on 2022-02-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0044_admin_add_expense_list_table_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_customer_report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tot_sales', models.CharField(max_length=100)),
                ('tot_amt', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_customer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=100)),
                ('customer_city', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='add_expense_list_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=100)),
                ('exp_date', models.CharField(max_length=100)),
                ('exp_category', models.EmailField(max_length=254)),
                ('amount', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_expense_report_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('exp_category', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_productlist_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_brand', models.CharField(max_length=100)),
                ('product_unit', models.CharField(max_length=100)),
                ('product_selling_price', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='add_purchase_tax_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('vendor', models.CharField(max_length=100)),
                ('p_tax', models.CharField(max_length=100)),
                ('g_tot', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_quotation_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('ref_number', models.CharField(max_length=100)),
                ('customer', models.EmailField(max_length=254)),
                ('customer_email', models.CharField(max_length=100)),
                ('g_total', models.CharField(max_length=100)),
                ('quo_note', models.CharField(max_length=200)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_return_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=254)),
                ('returned_dt', models.CharField(max_length=100)),
                ('returned_item', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_role_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(max_length=100)),
                ('profile', models.CharField(max_length=100)),
                ('notification', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_sale_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('sold_by', models.CharField(max_length=100)),
                ('sold_to', models.CharField(max_length=100)),
                ('items_sold', models.CharField(max_length=100)),
                ('payment', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_stock_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='add_vendor_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_phone', models.CharField(max_length=100)),
                ('vendor_city', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='addbrand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='addcategory_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='addtax_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_percentage', models.CharField(max_length=100)),
                ('tax_dafault', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='adduser_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('role_type', models.CharField(max_length=100)),
                ('status_type', models.CharField(max_length=100)),
                ('logger_id', models.CharField(max_length=200)),
            ],
        ),
    ]
